// Generated by scripts/generate_contracts.py. Edit backend/app/schemas.py instead.

export interface AnalyzeRequest {
  videoId: string;
  videoTitle: string;
  channelName: string;
  uploadDate?: string | null;
  durationSeconds?: number | null;
  transcript: string;
  language?: string | null;
  segments?: Array<TranscriptSegment>;
  analysisMode?: "evidence_first" | "evidence_only";
}

export interface AnalyzeResponse {
  videoId: string;
  analysisMode: "evidence_first" | "evidence_only";
  videoTitle: string;
  channelName: string;
  publishedAt: string;
  processingTimeMs: number;
  claims: Array<Claim>;
  limitations?: Array<string>;
}

export interface AuthTokenRequest {
  installationId: string;
  clientVersion?: string | null;
}

export interface AuthTokenResponse {
  token: string;
  tokenType?: string;
  expiresIn?: number;
}

export interface Claim {
  id: string;
  text: string;
  transcriptSnippet?: string | null;
  timestampStart?: number | null;
  timestampEnd?: number | null;
  temporalContext: TemporalContext;
  evidence?: Array<Evidence>;
  uncertainty: "supported" | "contradicted" | "contextualized" | "conflicting" | "insufficient_evidence";
  reflectionQuestions?: Array<string> | null;
}

export interface ClassifyRequest {
  text: string;
  threshold?: number | null;
}

export interface ClassifyResponse {
  label: string;
  dominant_label: string;
  verdict_pt: string;
  confidence: number;
  accepted: boolean;
  threshold: number;
  probabilities: Record<string, number>;
  top_features?: Array<Array<unknown>>;
  heuristic_reasons?: Array<string>;
  epistemic_tone?: string;
}

export interface Evidence {
  sourceId: string;
  relation: "supports" | "contradicts" | "contextualizes";
  title: string;
  url: string;
  publishedAt: string;
  publisher: string;
  snippet?: string | null;
  matchReason?: string | null;
  provenance: EvidenceProvenance;
}

export interface EvidenceProvenance {
  dataset: string;
  indexedAt: string;
  contentHash?: string | null;
}

export interface FeedbackRequest {
  videoId: string;
  rating: "positive" | "negative";
  reason?: "outdated_sources" | "insufficient_evidence" | "inaccurate" | "other" | null;
}

export interface FeedbackResponse {
  status?: "received";
  message?: string;
}

export interface HealthResponse {
  status: "healthy" | "degraded" | "unhealthy";
  version: string;
  services: Record<string, string>;
  timestamp: string;
}

export interface LivenessResponse {
  status?: "alive";
  timestamp: string;
}

export interface ReadinessResponse {
  status: "ready" | "not_ready";
  components: Record<string, string>;
  timestamp: string;
}

export interface TemporalContext {
  claimDate?: string | null;
  videoPublishedAt: string;
  note?: string | null;
}

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export type EvidenceRelation = Evidence["relation"];
export type UncertaintyState = Claim["uncertainty"];
export type FeedbackRating = FeedbackRequest["rating"];
export type FeedbackReason = NonNullable<FeedbackRequest["reason"]>;
export interface LocalCacheEntry extends AnalyzeResponse { timestamp: number; ttl: number; cacheVersion: number; }
export interface ApiErrorDetail { code: string; message: string; field?: string; }
export interface ErrorResponse { error: { code: string; message: string; details?: ApiErrorDetail[]; timestamp: string; }; }
