"""Generate JSON Schema and TypeScript from Pydantic; --check detects drift."""
import argparse
import json
import sys
from pydantic import BaseModel
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))
from app import schemas  # noqa: E402
from app.providers.reflection_catalog import REFLECTION_QUESTIONS  # noqa: E402


def build():
    definitions = {}
    for name in sorted(dir(schemas)):
        model = getattr(schemas, name)
        if not isinstance(model, type) or not issubclass(model, BaseModel) or model in (BaseModel, schemas.StrictModel):
            continue
        schema = model.model_json_schema(ref_template="#/definitions/{model}")
        definitions.update(schema.pop("$defs", {}))
        definitions[name] = schema
    document = {"$schema": "http://json-schema.org/draft-07/schema#", "title": "EvidencIA API Contract", "definitions": definitions}

    def ts(node):
        if "$ref" in node:
            return node["$ref"].rsplit("/", 1)[-1]
        if "anyOf" in node:
            return " | ".join(ts(part) for part in node["anyOf"])
        if "enum" in node:
            return " | ".join(json.dumps(value, ensure_ascii=False) for value in node["enum"])
        if "const" in node:
            return json.dumps(node["const"])
        kind = node.get("type")
        if kind == "array":
            return "Array<" + ts(node.get("items", {})) + ">"
        if kind == "object":
            return "Record<string, " + ts(node.get("additionalProperties", {})) + ">"
        return {"integer": "number", "number": "number", "string": "string", "boolean": "boolean", "null": "null"}.get(kind, "unknown")

    lines = ["// Generated by scripts/generate_contracts.py. Edit backend/app/schemas.py instead.", ""]
    for name, schema in sorted(definitions.items()):
        lines.append(f"export interface {name} {{")
        for field, node in schema.get("properties", {}).items():
            optional = "" if field in schema.get("required", []) else "?"
            lines.append(f"  {field}{optional}: {ts(node)};")
        lines += ["}", ""]
    lines += [
        'export type EvidenceRelation = Evidence["relation"];',
        'export type UncertaintyState = Claim["uncertainty"];',
        'export type FeedbackRating = FeedbackRequest["rating"];',
        'export type FeedbackReason = NonNullable<FeedbackRequest["reason"]>;',
        'export interface LocalCacheEntry extends AnalyzeResponse { timestamp: number; ttl: number; cacheVersion: number; }',
        'export interface ApiErrorDetail { code: string; message: string; field?: string; }',
        'export interface ErrorResponse { error: { code: string; message: string; details?: ApiErrorDetail[]; timestamp: string; }; }',
        '',
    ]
    return {ROOT / "shared/reflection-catalog.ts": "// Generated; edit app/providers/reflection_catalog.py instead.\nexport const REFLECTION_QUESTIONS = " + json.dumps(REFLECTION_QUESTIONS, ensure_ascii=False, indent=2) + " as const;\n", ROOT / "shared/schemas/api-schema.json": json.dumps(document, ensure_ascii=False, indent=2) + "\n", ROOT / "shared/types/api.ts": "\n".join(lines)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in build().items():
        if args.check:
            if path.read_text() != content:
                raise SystemExit(f"Contrato desatualizado: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
